server:
  port: 8081

spring:
  application:
    name: search-service
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms

aws:
  access:
    key:
      id: ${AWS_ACCESS_KEY_ID:your-access-key-id}
  secret:
    access:
      key: ${AWS_SECRET_ACCESS_KEY:your-secret-access-key}
  region: ${AWS_DEFAULT_REGION:us-east-1}
  dynamodb:
    endpoint: ${DYNAMODB_ENDPOINT:}

logging:
  level:
    com.flightbooking.searchservice: DEBUG
    org.springframework.data.redis: DEBUG 