aws:
  access:
    key:
      id: local
  secret:
    access:
      key: local
  region: us-east-1
  dynamodb:
    endpoint: http://localhost:8000

server:
  port: 8081

spring:
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms

logging:
  level:
    com.flightbooking.searchservice: DEBUG
    com.amazonaws: DEBUG 